import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Providers from './providers'
import OffCanvas from '@/components/OffCanvas'
import MobileMenuButton from '@/components/MobileMenuButton'
import ThemeSwitcher from '@/components/ThemeSwitcher'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Providers>
        <OffCanvas/>
        <ThemeSwitcher/>
        {children}
      </Providers>
      </body>
    </html>
  )
}
